os: osx # at least until https://github.com/tcoopman/image-webpack-loader/issues/142 is fixed
language: node_js

node_js:
  - 8

script: echo -e "RAVEN_DSN=nope\nDEV_DOMAIN=nope" >> ./.env && npm run test && npm run build

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
