language: node_js

node_js:
  - 8
  - 7

script: npm run build

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  # comment out the below lines to prevent caching node_modules if pngquant-bin fails to compile!
  directories:
    - node_modules
